const ErrorCodes = Object.freeze({
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    RATE_LIMITED: 'RATE_LIMITED',

    DB_UNAVAILABLE: 'DB_UNAVAILABLE',
    DB_OPERATION_FAILED: 'DB_OPERATION_FAILED',

    STRIPE_ERROR: 'STRIPE_ERROR',
    STRIPE_TIMEOUT: 'STRIPE_TIMEOUT',
    STRIPE_INTENT_NOT_UPDATEABLE: 'STRIPE_INTENT_NOT_UPDATEABLE',

    CHECKOUT_STALE: 'CHECKOUT_STALE',
    CHECKOUT_EMPTY: 'CHECKOUT_EMPTY',
    CART_NOT_FOUND: 'CART_NOT_FOUND',
    CART_STALE: 'CART_STALE',
    CART_CONFLICT: 'CART_CONFLICT',
    SHIPPING_METHOD_INVALID: 'SHIPPING_METHOD_INVALID',
    SHIPPING_UNAVAILABLE: 'SHIPPING_UNAVAILABLE',
    SHIPPING_STALE: 'SHIPPING_STALE',

    DISCOUNT_INVALID: 'DISCOUNT_INVALID',
    DISCOUNT_EXPIRED: 'DISCOUNT_EXPIRED',
    DISCOUNT_ALREADY_USED: 'DISCOUNT_ALREADY_USED',
    DISCOUNT_UNAVAILABLE: 'DISCOUNT_UNAVAILABLE',

    INTERNAL_ERROR: 'INTERNAL_ERROR'
});

module.exports = { ErrorCodes };
